name: CI

on: [push, fork, pull_request, workflow_dispatch]

env:
  UV_SYSTEM_PYTHON: true

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@master

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install uv --disable-pip-version-check
          uv pip install -r pyproject.toml --system
      - name: Check code quality
        run: |
          ruff format --check --diff
          ruff check --diff
      - name: Type Check
        run: |
          yarn global add pyright
          pyright
